name: vdfrsa
description: Dart implementation of Wesolowski RSA-group VDF
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.0
  native_toolchain_c: ^0.17.6
